### ISSUE TITLE
typing error

### ISSUE THREAD

**Issue by jakinpilla** [CanDoVueJS/report#2]
(p.189) Memo 컴포넌트는 직접적인 삭제를 하지 않고 부모 컴포넌트인 삭제의 책임을 위임하되...

-> Memo 컴포넌트는 직접적인 삭제를 하지 않고 부모 컴포넌트인 MemoApp 컴포넌트로 삭제의 책임을 위임하되...

**Comment by MartinYounghoonKim** [comment]
@jakinpilla 제보 감사합니다. 
이후 배포본에 반영하도록 하겠습니다.
