### ISSUE TITLE
309p 내용수정

### ISSUE THREAD

**Issue by silica67sdm** [CanDoVueJS/report#5]
'src 디렉터리에 pages 디렉터리를 생성하고 ~' => '앞에서 생성한 src 디렉터리에 pages 디렉터리에 Signup.vue파일을 생성한다' 로 변경해야 할 거 같습니다.

**Comment by evan-moon** [comment]
안녕하세요 @silica67sdm 님, 제보 감사합니다!
이 부분은 오타라기보다 문맥의 흐름 개선에 조금 더 가까운 것 같네요 :)

오타나 코드의 오류 같은 경우는 논리적으로 명백히 틀린 사항이기 때문에 리포트에 게재하고 있지만, 문맥의 흐름 같은 경우는 사람마다 해석의 여지가 다른 부분이기 때문에 리포트에 게재하는 것은 조금 어려울 것 같아요.

회원가입 페이지를 구현하는 시점에서는 이미 `src` 디렉토리가 생성되어있기 때문에 `src` 디렉토리를 한번 더 생성할 가능성 자체는 낮다고 사료됩니다. 말씀해주신대로 "앞에서 생성한" 이라는 문장이 포함했다면 좀 더 명확한 의사전달이 되었을 것 같아서 아쉽네요.

피드백 감사합니다! 좋은 하루 되세요 :)
